#!/usr/bin/env python3
"""
生成简单测试 PDF 文件

模块: 03-小工具开发
知识点: PDF 操作
Python 版本: >= 3.9
最后验证: 2025-07-15

运行方式:
    python generate_sample_pdf.py

描述:
    使用纯 Python 手动构建最小化的 PDF 文件，不依赖任何第三方库。
    生成的 PDF 包含两页简单文本内容，可用于测试 pdf_info.py。

    PDF 文件格式基于 Adobe PDF 规范，由以下部分组成：
    - Header: PDF 版本声明
    - Body: 对象定义（页面树、页面、字体、内容流）
    - Cross-reference table: 对象偏移量索引
    - Trailer: 文件入口信息
"""

from pathlib import Path


def build_minimal_pdf(title: str = "Sample PDF", author: str = "Python") -> bytes:
    """构建一个最小化的两页 PDF 文件。

    Args:
        title: PDF 标题元数据
        author: PDF 作者元数据

    Returns:
        PDF 文件的字节内容
    """
    # PDF 对象列表，记录每个对象的偏移量
    objects = []
    content = b"%PDF-1.4\n"

    def add_object(obj_data: str) -> int:
        """添加一个 PDF 对象，返回对象编号。"""
        nonlocal content
        obj_num = len(objects) + 1
        objects.append(len(content))
        content += f"{obj_num} 0 obj\n{obj_data}\nendobj\n".encode("latin-1")
        return obj_num

    # 对象 1: Catalog（文档目录）
    add_object("<< /Type /Catalog /Pages 2 0 R >>")

    # 对象 2: Pages（页面树）
    add_object("<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>")

    # 对象 3: 第一页
    add_object(
        "<< /Type /Page /Parent 2 0 R "
        "/MediaBox [0 0 612 792] "
        "/Contents 5 0 R /Resources << /Font << /F1 7 0 R >> >> >>"
    )

    # 对象 4: 第二页
    add_object(
        "<< /Type /Page /Parent 2 0 R "
        "/MediaBox [0 0 612 792] "
        "/Contents 6 0 R /Resources << /Font << /F1 7 0 R >> >> >>"
    )

    # 对象 5: 第一页内容流
    page1_text = (
        "BT /F1 24 Tf 100 700 Td (Sample PDF Document) Tj ET\n"
        "BT /F1 14 Tf 100 650 Td (Page 1 - Generated by Python) Tj ET\n"
        "BT /F1 12 Tf 100 600 Td (This PDF was created without any third-party libraries.) Tj ET\n"
    )
    add_object(f"<< /Length {len(page1_text)} >>\nstream\n{page1_text}endstream")

    # 对象 6: 第二页内容流
    page2_text = (
        "BT /F1 24 Tf 100 700 Td (Page 2) Tj ET\n"
        "BT /F1 12 Tf 100 650 Td (This is the second page of the sample PDF.) Tj ET\n"
    )
    add_object(f"<< /Length {len(page2_text)} >>\nstream\n{page2_text}endstream")

    # 对象 7: 字体
    add_object(
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
    )

    # 对象 8: 文档信息（元数据）
    info_num = add_object(
        f"<< /Title ({title}) /Author ({author}) "
        f"/Creator (generate_sample_pdf.py) /Producer (Pure Python PDF Generator) >>"
    )

    # 交叉引用表
    xref_offset = len(content)
    content += b"xref\n"
    content += f"0 {len(objects) + 1}\n".encode()
    content += b"0000000000 65535 f \n"
    for offset in objects:
        content += f"{offset:010d} 00000 n \n".encode()

    # Trailer
    content += b"trailer\n"
    content += f"<< /Size {len(objects) + 1} /Root 1 0 R /Info {info_num} 0 R >>\n".encode()
    content += b"startxref\n"
    content += f"{xref_offset}\n".encode()
    content += b"%%EOF\n"

    return content


def main():
    """生成示例 PDF 文件。"""
    script_dir = Path(__file__).parent
    output_file = script_dir / "sample.pdf"

    pdf_bytes = build_minimal_pdf(
        title="示例 PDF 文档",
        author="Python 学习知识库",
    )

    output_file.write_bytes(pdf_bytes)
    print(f"已生成示例 PDF: {output_file}")
    print(f"文件大小: {len(pdf_bytes)} 字节")
    print("包含 2 页，可用 PDF 阅读器打开查看。")


if __name__ == "__main__":
    main()
